<script lang="ts">
	import { SITE_URL, GITHUB_REPO } from '$lib/config/site';
</script>

<svelte:head>
	<title>Terms of Use — Utsuwa</title>
	<meta
		name="description"
		content="The terms that govern the Utsuwa website, hosted web app, and desktop app."
	/>
	<link rel="canonical" href={`${SITE_URL}/terms`} />
	<meta property="og:type" content="website" />
	<meta property="og:title" content="Terms of Use — Utsuwa" />
	<meta
		property="og:description"
		content="The terms that govern the Utsuwa website, hosted web app, and desktop app."
	/>
	<meta property="og:url" content={`${SITE_URL}/terms`} />
	<meta property="og:site_name" content="Utsuwa" />
</svelte:head>

<header class="legal-header">
	<h1>Terms of Use</h1>
	<p class="legal-date">Effective: July 3, 2026</p>
</header>

<article class="prose legal-prose">
	<p>
		Thanks for using Utsuwa. These terms cover the Utsuwa website and hosted services at
		utsuwa.ai (including app.utsuwa.ai and docs.utsuwa.ai) and the Utsuwa desktop app, operated by
		Juice Boxx Games LLC ("we", "us"), a limited liability company formed in Ohio, USA.
		Utsuwa's source code is open source and separately licensed under the
		<a href={`${GITHUB_REPO}/blob/main/LICENSE`} target="_blank" rel="noopener noreferrer">GNU AGPL-3.0-or-later</a>; nothing in these terms limits the rights that license gives you. By using Utsuwa,
		you agree to these terms.
	</p>

	<h2 id="what-utsuwa-is">What Utsuwa is (and isn't)</h2>
	<p>
		Utsuwa is an AI companion: software that renders an animated character and connects it to AI
		models so you can talk with it. It's built for companionship, creativity, and fun.
	</p>
	<p>
		It is not a person, and it is not a professional. Nothing your companion says is medical,
		mental-health, legal, financial, or other professional advice, and it is not a substitute for
		care from a qualified human. If you are going through a crisis, please don't rely on an AI
		companion: in the US you can call or text 988 (the Suicide &amp; Crisis Lifeline); elsewhere,
		contact your local emergency or crisis services.
	</p>

	<h2 id="your-provider">Your AI provider, your keys</h2>
	<p>
		Utsuwa does not include an AI model. You connect a provider of your choice using your own API
		key, or run a local model on your own hardware. You are responsible for keeping your keys
		secure, for any costs your provider charges, and for complying with your provider's terms of
		service. Your companion's responses are generated by the third-party model you selected; we do
		not author, control, or review them.
	</p>

	<h2 id="ai-content">AI-generated content</h2>
	<p>
		AI output can be inaccurate, incomplete, or entirely fictional, even when it sounds confident.
		Your companion's personality, emotions, and memories are simulations driven by your
		configuration and your chosen model. Use your own judgment before relying on or sharing
		anything it produces; you are responsible for how you use it.
	</p>

	<h2 id="acceptable-use">Acceptable use</h2>
	<p>
		Use Utsuwa lawfully. Don't interfere with, disrupt, or overload our hosted services or attempt
		to circumvent their protections; don't use our relay to violate your AI provider's policies;
		and don't misrepresent yourself as affiliated with Utsuwa or Juice Boxx Games LLC.
	</p>

	<h2 id="no-crypto">No crypto, ever</h2>
	<p>
		Utsuwa has no cryptocurrency, token, NFT, or blockchain project of any kind, and never will.
		Anyone claiming otherwise, including forks of our code with a token attached, is not
		affiliated with us.
	</p>

	<h2 id="open-source">Open source and ownership</h2>
	<p>
		Utsuwa's code is licensed under the
		<a href={`${GITHUB_REPO}/blob/main/LICENSE`} target="_blank" rel="noopener noreferrer">GNU AGPL-3.0-or-later</a>, and these terms don't restrict what that license permits you to do with the code.
		These terms govern your use of our website and hosted services. The Utsuwa name, logo, and
		branding belong to Juice Boxx Games LLC; please don't use them in ways that imply
		endorsement or affiliation. Avatar models, animations, and other assets you import remain
		yours, subject to whatever licenses they came with.
	</p>

	<h2 id="age">Age</h2>
	<p>
		Utsuwa is for adults. You must be at least 18 years old to use it; it is not designed or
		intended for anyone under 18.
	</p>

	<h2 id="as-is">Utsuwa is provided "as is"</h2>
	<p>
		Utsuwa is free software provided "as is" and "as available", without warranties of any kind,
		express or implied, including warranties of merchantability, fitness for a particular purpose,
		and non-infringement. We don't promise that Utsuwa will be uninterrupted, error-free, or that
		its output will be accurate.
	</p>

	<h2 id="liability">Limitation of liability</h2>
	<p>
		To the maximum extent permitted by law, Juice Boxx Games LLC and its members and
		contributors will not be liable for any indirect, incidental, special, consequential, or
		exemplary damages, or for lost profits, data, or goodwill, arising from your use of Utsuwa.
		Our total liability for any claim relating to Utsuwa will not exceed fifty US dollars (US $50)
		or the amount you have paid us to use Utsuwa in the past twelve months, whichever is greater.
	</p>

	<h2 id="governing-law">Governing law</h2>
	<p>
		These terms are governed by the laws of the State of Ohio, USA, without regard to its
		conflict-of-laws rules. Any dispute relating to these terms will be resolved in the state or
		federal courts located in Ohio.
	</p>

	<h2 id="changes">Changes to these terms</h2>
	<p>
		We may update these terms from time to time. If we do, we'll update this page and the date at
		the top. Continuing to use Utsuwa after a change means you accept the updated terms.
	</p>

	<h2 id="contact">Contact</h2>
	<p>
		The fastest way to reach us is on
		<a href={`${GITHUB_REPO}/issues`} target="_blank" rel="noopener noreferrer">GitHub</a>.
	</p>
</article>

<style>
	.legal-header {
		text-align: center;
		margin: 0 0 2.5rem;
	}

	.legal-header h1 {
		font-size: clamp(2.25rem, 5vw, 3rem);
		font-weight: 700;
		line-height: 1.1;
		letter-spacing: -0.02em;
		color: var(--text-primary);
		margin: 0 0 1rem;
	}

	.legal-date {
		font-size: 0.8125rem;
		font-weight: 500;
		color: var(--text-secondary);
		margin: 0;
	}

	.legal-prose {
		min-width: 0;
	}

	.legal-header {
		animation: legalEnter 0.6s cubic-bezier(0.16, 1, 0.3, 1) both;
	}

	@keyframes legalEnter {
		from {
			opacity: 0;
			transform: translateY(12px);
		}
		to {
			opacity: 1;
			transform: translateY(0);
		}
	}
</style>
